#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar
# Load Notification Manager
# exec-once = dunst
exec-once = swaync
# Set a wallpaper
exec-once = swww-daemon
# exec-once = swww img ~/Pictures/Wallpapers/triangles.jpeg --transition-type center
# Start nextcloud sync
exec-once = nextcloud
# Start Polkit
exec-once = /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
# lock the screen after idle time ~/.config/swayidle/config
exec-once = swayidle -w timeout 1800 'swaylock -f' timeout 1805 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
# Newtwork manager
exec-once = nm-applet --indicator
# Bluetooth manager
exec-once = blueman-applet
# Add copied items to the clipboard history
exec-once = wl-paste --watch cliphist store
# start pyprland
exec-once = ~/.local/bin/pypr