-- #######################################################################################
-- Hyprland Lua config (migrated from hyprland.conf for Hyprland >= 0.55)
-- https://wiki.hypr.land/Configuring/Start/
-- #######################################################################################

hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Format: output, resolution@refresh, position, scale
--
-- Display mode management (cycled by scripts/display-cycle.sh):
--   laptop   -> only the laptop screen (eDP-1) is on
--   both     -> laptop + Samsung (DP-2) both on
--   external -> only the Samsung (DP-2) is on
--
--   * Preference stored in ~/.config/hypr/state/display-mode.
--   * Falls back to "laptop" whenever the Samsung (DP-2) is NOT connected, so
--     we are never left without a usable screen.
--   * Cycled by the keybind + scripts/display-cycle.sh, then `hyprctl reload`.
local HOME = os.getenv("HOME")

local function display_mode()
	local f = io.open(HOME .. "/.config/hypr/state/display-mode", "r")
	if not f then return "both" end
	local v = f:read("*a") or ""
	f:close()
	v = v:gsub("%s+", "")
	if v == "laptop" or v == "both" or v == "external" then return v end
	return "both"
end

-- Samsung present? hl.get_monitor returns nil if the output is not connected.
local samsung_connected = hl.get_monitor("DP-2") ~= nil
-- Without the Samsung connected, the only sensible mode is "laptop".
local mode              = samsung_connected and display_mode() or "laptop"

local laptop_on   = (mode == "laptop" or mode == "both")
local external_on = samsung_connected and (mode == "both" or mode == "external")

-- Laptop panel (4K) at scale 2.0 -> effective 1920x1080, placed at top-left.
hl.monitor({
	output   = "eDP-1",
	mode     = "3840x2160@60",
	position = "0x0",
	scale    = 2.0,
	disabled = not laptop_on,
})

-- Samsung 4K monitor, placed to the right of the laptop (x = 1920 logical px).
-- Scale 1.25 -> effective 3072x1728 (a bit smaller UI / more space).
hl.monitor({
	output   = "DP-2",
	mode     = "3840x2160@60",
	position = "1920x0",
	scale    = 1.25,
	disabled = not external_on,
})

-- Fallback for any other monitor that gets plugged in.
hl.monitor({
	output   = "",
	mode     = "preferred",
	position = "auto",
	scale    = "auto",
})

-- Re-evaluate the laptop-screen rule when the Samsung is docked/undocked.
-- Only react to DP-2 so we don't loop when eDP-1 itself is added/removed.
hl.on("monitor.added", function(mon)
	if mon and mon.name == "DP-2" then
		hl.exec_cmd("hyprctl reload")
	end
end)

hl.on("monitor.removed", function(mon)
	if mon and mon.name == "DP-2" then
		hl.exec_cmd("hyprctl reload")
	end
end)

---------------------
---- MY PROGRAMS ----
---------------------
local terminal    = "kitty"
local fileManager = "nautilus"
local menu        = "wofi --show drun --allow-images -W 30% -p Run -D key_expand=Tab"

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRSHOT_DIR", HOME .. "/Pictures/Screenshots")
-- AGS/Astal typelibs live under /usr/local (meson default prefix); AstalTray under ~/.local
hl.env("GI_TYPELIB_PATH", "/usr/local/lib/x86_64-linux-gnu/girepository-1.0:" .. HOME .. "/.local/lib/x86_64-linux-gnu/girepository-1.0")
hl.env("LD_LIBRARY_PATH", HOME .. "/.local/lib/x86_64-linux-gnu:/usr/local/lib/x86_64-linux-gnu")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Load pywal-generated colors (~/.cache/wal/colors-hyprland.conf is hyprlang
-- format: "$colorN = rgba(r,g,b,a)"). We parse it into a Lua table here so the
-- pywal workflow keeps working: regenerate colors then `hyprctl reload`.
local function load_wal()
	local colors = {}
	local f = io.open(os.getenv("HOME") .. "/.cache/wal/colors-hyprland.conf", "r")
	if not f then return colors end
	for line in f:lines() do
		local k, v = line:match("^%s*%$(%S+)%s*=%s*(.-)%s*$")
		if k and v then colors[k] = v end
	end
	f:close()
	return colors
end

local wal            = load_wal()
local activeBorder   = {
	colors = { wal.color1 or "rgba(33ccffee)",
		wal.color1 or "rgba(33ccffee)",
		wal.color2 or "rgba(00ff99ee)" },
	angle = 45
}
local inactiveBorder = wal.background or "rgba(595959aa)"

hl.config({
	general = {
		gaps_in          = 3,
		gaps_out         = 6,
		border_size      = 1,

		col              = {
			active_border   = activeBorder,
			inactive_border = inactiveBorder,
		},

		resize_on_border = false,
		allow_tearing    = false,
		layout           = "dwindle",
	},

	decoration = {
		rounding         = 10,
		active_opacity   = 1.0,
		inactive_opacity = 0.8,

		shadow           = {
			enabled      = true,
			range        = 4,
			render_power = 3,
			color        = "rgba(1a1a1aee)",
		},

		blur             = {
			enabled  = true,
			size     = 3,
			passes   = 2,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},

	dwindle = {
		preserve_split = true,
	},

	master = {
		new_status = "master",
	},

	cursor = {
		no_hardware_cursors = true, -- software cursors update every frame (smooth plugin animation)
	},
	misc = {
		force_default_wallpaper  = -1,
		disable_hyprland_logo    = false,
		disable_splash_rendering = true,
		-- Wake displays from DPMS-off on any input (so the lock screen reappears).
		mouse_move_enables_dpms  = true,
		key_press_enables_dpms   = true,
	},
})

-- Animations
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "default", style = "slidefadevert -20%" })

---------------
---- INPUT ----
---------------
hl.config({
	input = {
		kb_layout                   = "us,de",
		kb_options                  = "",
		kb_variant                  = "",
		kb_model                    = "",
		kb_rules                    = "",

		follow_mouse                = 1,
		float_switch_override_focus = 0,
		sensitivity                 = 0,

		touchpad                    = {
			natural_scroll = false,
		},
	},
})

hl.gesture({
	fingers   = 3,
	direction = "horizontal",
	action    = "workspace",
})

hl.device({
	name        = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------
require("keybindings")

-------------------
---- AUTOSTART ----
-------------------
require("autostart")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Ignore maximize requests from all apps.
hl.window_rule({
	name           = "suppress-maximize-events",
	match          = { class = ".*" },
	suppress_event = "maximize",
})

-- No border on single-window tiled workspaces
hl.window_rule({
	match       = { workspace = "w[t1]" },
	border_size = 0,
})

-- Browser Picture in Picture / Discord Popout
local pipMatch = { title = "(Picture-in-Picture)|(Discord Popout)" }
hl.window_rule({ match = pipMatch, pin = true })
hl.window_rule({ match = pipMatch, move = { "monitor_w*0.605", "monitor_h*0.04" } })
hl.window_rule({ match = pipMatch, float = true })
hl.window_rule({ match = pipMatch, no_dim = true })
hl.window_rule({ match = pipMatch, opaque = true })
hl.window_rule({ match = pipMatch, no_initial_focus = true })
hl.window_rule({ match = pipMatch, keep_aspect_ratio = true })

-- Shell with transparent background
hl.window_rule({ match = { class = "kitty" }, opacity = "0.94" })

-- KeePassXC
hl.window_rule({ match = { class = "(.*)(keepassxc)(.*)$" }, float = true })

-- mpv
hl.window_rule({ match = { class = "mpv" }, keep_aspect_ratio = true })
hl.window_rule({ match = { title = "(mpv)" }, opaque = true })

-- Nextcloud
hl.window_rule({ match = { title = "(Nextcloud)" }, float = true })
hl.window_rule({ match = { title = "(Nextcloud)" }, move = { 1450, 590 } })

-- Zoom: float popups/toolbars only (main meeting window stays tiled)
-- Native Wayland Zoom uses class "Zoom"; toolbars have these titles.
local zoomPopups = { class = "^(Zoom)$", title = "(as_toolbar)|(annotate_toolbar)|(zoom_linux_float_video_window)|(menu window)|(confirm window)|(Leave meeting panel)" }
hl.window_rule({ match = zoomPopups, float = true })
-- Keep transient popups (menus / breakout-join) from vanishing on mouse move
hl.window_rule({ match = { class = "^(Zoom)$", title = "(menu window)|(confirm window)|(Leave meeting panel)" }, stay_focused = true })
-- Pin toolbar + floating video/participants view so they show on all workspaces
hl.window_rule({ match = { class = "^(Zoom)$", title = "(as_toolbar)|(annotate_toolbar)|(zoom_linux_float_video_window)" }, pin = true })
-- Default positions (monitor-relative)
hl.window_rule({ match = { class = "^(Zoom)$", title = "(as_toolbar)" }, move = { 1127, 17 } })
hl.window_rule({ match = { class = "^(Zoom)$", title = "(zoom_linux_float_video_window)" }, move = { 2821, 256 } })
hl.window_rule({ match = { class = "^(Zoom)$", title = "(annotate_toolbar)" }, move = { 2893, 1560 } })

-- Layer rules
hl.layer_rule({ match = { namespace = "wofi" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi" }, ignore_alpha = 0 })

-- ── hypr-dynamic-cursors ───────────────────────────────────────────────────
if hl.plugin.dynamic_cursors then
	-- Persist the mode chosen from the Waybar mouse-effect icon across reloads.
	local function cursor_mode()
		local f = io.open(HOME .. "/.config/hypr/state/cursor-mode", "r")
		if not f then return "stretch" end
		local v = (f:read("*a") or ""):gsub("%s+", "")
		f:close()
		if v == "none" or v == "tilt" or v == "rotate" or v == "stretch" then
			return v
		end
		return "stretch"
	end

	hl.config { plugin = { dynamic_cursors = {
		enabled    = true,
		mode       = cursor_mode(), -- tilt | rotate | stretch | none (set via Waybar icon)
		threshold  = 1,       -- lower = more frequent shape updates

		-- rotate     = {
		-- 	length = 20,       -- px, ideally matches your cursor size
		-- 	offset = 0.0,
		-- },

		-- for mode = "tilt" — tilt the cursor based on x-velocity
		tilt = {
			limit      = 1500,                 -- speed (px/s) for full tilt (lower = tilts more easily)
			activation = "negative_quadratic", -- linear | quadratic | negative_quadratic (most aggressive)
			window     = 100,                  -- ms over which speed is calculated
			full       = 85,                   -- full tilt for each side (°) — higher = more tilt
		},

		-- for mode = "stretch" — stretch the cursor shape based on direction and velocity
		stretch    = {
			limit      = 1000,              -- LOW = very pronounced (full 2x stretch reached at slow speed)
			activation = "negative_quadratic", -- linear | quadratic | negative_quadratic (most aggressive)
			window     = 100,               -- ms over which speed is calculated (higher = smoother but more delayed)
		},

		shake      = {
			enabled   = true, -- shake mouse to magnify cursor (easy to find)
			threshold = 4.0,
			base      = 4.0,
			speed     = 4.0,
			timeout   = 2000,
		},

		hyprcursor = {
			enabled    = true,
			nearest    = 1,
			resolution = -1,
		},
	} } }
end
